from __future__ import annotations
from fpdf import FPDF
from datetime import datetime
import os

class EvaluationReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'BidInsight AI - Procurement Evaluation Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by BidInsight AI on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def generate_evaluation_pdf(summary: dict, output_path: str):
    pdf = EvaluationReport()
    pdf.add_page()
    
    # Vendor Info Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Vendor Details', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, f"Vendor Name: {summary.get('vendor_name', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Vendor ID: {summary.get('vendor_id', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Overall Status: {summary.get('overall_status', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Confidence Score: {summary.get('overall_confidence_score', 0)}%", 0, 1)
    pdf.ln(5)

    # Recommendation Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Final Recommendation', 0, 1)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 8, summary.get('final_recommendation', 'No recommendation provided.'))
    pdf.ln(5)

    # Criteria Table
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Criterion-Level Evaluation', 0, 1)
    
    # Table Header
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(60, 10, 'Criterion', 1)
    pdf.cell(30, 10, 'Status', 1)
    pdf.cell(30, 10, 'Confidence', 1)
    pdf.cell(70, 10, 'Source Document', 1)
    pdf.ln()

    # Table Rows
    pdf.set_font('Arial', '', 8)
    for c in summary.get('criteria_evaluation', []):
        pdf.cell(60, 8, c.get('criterion_name', '')[:35], 1)
        pdf.cell(30, 8, c.get('status', ''), 1)
        pdf.cell(30, 8, f"{c.get('confidence_score', 0)}%", 1)
        pdf.cell(70, 8, c.get('source_document', '')[:40], 1)
        pdf.ln()
    
    pdf.ln(10)
    
    # Risk Flags
    if summary.get('risk_flags'):
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'Risk Flags & Manual Review Cases', 0, 1)
        pdf.set_font('Arial', '', 10)
        for flag in summary.get('risk_flags', []):
            pdf.multi_cell(0, 8, f"- {flag}")
        pdf.ln(5)

    # Audit Summary
    audit = summary.get('audit_summary', {})
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 10, 'Audit Trail', 0, 1)
    pdf.set_font('Arial', '', 8)
    pdf.cell(0, 8, f"Processed At: {audit.get('processed_at', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Review Required: {'Yes' if audit.get('review_required') else 'No'}", 0, 1)
    
    pdf.output(output_path)
    return output_path
